### ISSUE TITLE
JavaScript Capstone Group Project

### ISSUE THREAD

**Issue by Haywayaheadshot** [Haywayaheadshot/javascript-capstone#21]
### Hi

Please find included in this issue the link to our capstone project repo. We are two group members. @Haywayaheadshot, @taldr27 

Thank you

Github repo link - https://github.com/Haywayaheadshot/javascript-capstone

**Comment by DeliceLydia** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Haywayaheadshot** [comment]
Thank you @DeliceLydia
