### ISSUE TITLE
Peer-to-peer review

### ISSUE THREAD

**Issue by MattGomb** [Haywayaheadshot/javascript-capstone#25]
😎 Great work, the project looks very nice, the API fetch is very clean, and you are way ahead of schedule! 👍🏻  💯 

For only displaying a certain number of cards, you could for example: 
- use the counter to hide all cards after the first 20 (or any number you want), with for example style.display
- create a button 
- every time you click the button, you can change the style.display of the next batch of the cards (for example you can reveal always the next 20)

**Comment by J2ZROMERO** [comment]
- Good job so far:  it could be better if the footer content will be wrapped with an H or P tag, span tag is more used for applying extra styles, and H,P tag if for defining content.

**Comment by carreraprogrammer** [comment]
Good job so far! [🎉](https://emojipedia.org/party-popper/)

As Matt said above, I kindly recommend you use different strategies to display a certain number of cards. Another example could be the use of the property Overflow on the Y-axis and the width to take control of the number of cards that you could display

**Comment by Haywayaheadshot** [comment]
> * Good job so far:  it could be better if the footer content will be wrapped with an H or P tag, span tag is more used for applying extra styles, and H,P tag if for defining content.

Thanks @J2ZROMERO I will work on this asap

**Comment by Haywayaheadshot** [comment]
> 😎 Great work, the project looks very nice, the API fetch is very clean, and you are way ahead of schedule! 👍🏻 💯
> 
> For only displaying a certain number of cards, you could for example:
> 
> * use the counter to hide all cards after the first 20 (or any number you want), with for example style.display
> * create a button
> * every time you click the button, you can change the style.display of the next batch of the cards (for example you can reveal always the next 20)

Thank you @MattGomb I will reach out once I implement this feature. Just to check if I have done it correctly

**Comment by Haywayaheadshot** [comment]
> Good job so far! [🎉](https://emojipedia.org/party-popper/)
> 
> As Matt said above, I kindly recommend you use different strategies to display a certain number of cards. Another example could be the use of the property Overflow on the Y-axis and the width to take control of the number of cards that you could display

Thanks @carreraprogrammer I will implement both your idea and @MattGomb idea to see which one works better.
